# Generated by Django 5.2.3 on 2025-07-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tela', models.CharField(max_length=100)),
                ('talle', models.TextField()),
                ('color', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mostrar_en_carrusel', models.BooleanField(default=False)),
                ('es_hotsale', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('campera-camisaco', 'Campera / Camisaco'), ('camisas', 'Camisas'), ('pantalon-jeans', 'Pantalón / Jeans'), ('remeras-top', 'Remeras / Top'), ('vestidos', 'Vestidos'), ('polleras', 'Polleras'), ('corset', 'Corset')], max_length=50)),
            ],
            options={
                'db_table': 'prenda',
            },
        ),
        migrations.CreateModel(
            name='Imagen_prenda',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.TextField()),
                ('orden', models.IntegerField(default=1)),
                ('prenda', models.ForeignKey(db_column='prenda_id', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.prenda')),
            ],
            options={
                'db_table': 'imagenes_prenda',
                'ordering': ['orden'],
            },
        ),
    ]
