from django.urls import path
from . import views

urlpatterns = [
    path('',views.inicio, name='inicio'),
    path("api/favoritos", views.favoritos_api, name="favoritos_api"),
    path('prenda/<int:prenda_id>/', views.detalle_prenda, name='detalle_prenda'),
    path("buscar/", views.buscar_prendas, name="buscar_prendas"),
    path('añadir-al-carrito/<int:prenda_id>/', views.añadir_al_carrito, name='añadir_al_carrito'),
    path('carrito/eliminar/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path("carrito/", views.carrito, name="carrito"),
    path('inicio_sesion/', views.inicio_sesion, name='inicio_sesion'),
    path('recuperar/', views.recuperar_contrasena, name='recuperar_contrasena'),
    path('nueva-contrasena/', views.nueva_contrasena, name='nueva_contrasena'),
    path('registro/', views.registro, name='registro'),
    path("verificacion/", views.verificacion_email, name="verificacion_email"),
    path("confirmacion/", views.confirmacion_email, name="confirmacion_email"),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path("confirmar_pedido/", views.confirmar_pedido, name="confirmar_pedido"),
    path("solicitar_pedido/", views.solicitar_pedido, name="solicitar_pedido"),
    path('panel_admin/', views.panel_admin, name='panel_admin'),
    path('admin/prenda/agregar/', views.agregar_prenda, name='agregar_prenda'),
    path("admin/eliminar/", views.buscar_eliminar_prendas, name="buscar_eliminar_prendas"),
    path('admin/eliminar/confirmar/', views.confirmar_eliminacion_prendas, name='confirmar_eliminacion_prendas'),
    path('admin/modificar/', views.buscar_modificar_prendas, name='buscar_modificar_prendas'),
    path('admin/modificar/<int:prenda_id>/', views.modificar_prenda, name='modificar_prenda'),
    path('admin/inicio/', views.admin_inicio_prendas, name='admin_inicio_prendas'),
    path('admin/hotsale/', views.admin_hotsale_prendas, name='admin_hotsale_prendas'),
    path('categoria/<str:categoria_slug>/', views.productos_por_categoria, name='productos_por_categoria'),
]